import { usePage } from '@inertiajs/react';

export const translations = {
    en: {
        dashboard: 'Dashboard', products: 'Products', purchases: 'Purchases / Stock In', stockAdjustments: 'Stock Adjustments', salesInvoice: 'Sales & Invoice', reports: 'Reports', suppliers: 'Suppliers', categories: 'Categories', security: 'Security', usersAccess: 'Users & Access', activityLogs: 'Activity Logs', notifications: 'System Notifications', lowStockProducts: 'Low stock products', expiringMedicines: 'Expiring medicines within 1 month', expiredMedicines: 'Expired medicines', language: 'Language', english: 'English', bangla: 'বাংলা', logout: 'Logout', shopSubtitle: 'Chokh seba and optical shop management', totalProducts: 'Total Products', medicines: 'Medicines', glassItems: 'Glass Items', lowStock: 'Low Stock', expiringSoon: 'Expiring Soon', todaySales: 'Today Sales', monthlySales: 'Monthly Sales', todayPurchase: 'Today Purchase', monthlyPurchase: 'Monthly Purchase', quickOverview: 'Quick Overview', inventoryHealth: 'Inventory Health', businessSummary: 'Business Summary', recentSales: 'Recent Sales', recentPurchases: 'Recent Purchases / Stock In', recentStockMovements: 'Recent Stock Movements', noLowStock: 'No low stock product found.', noExpiring: 'No medicine expiring within 1 month.', invoice: 'Invoice', customer: 'Customer', total: 'Total', paid: 'Paid', due: 'Due', status: 'Status', purchase: 'Purchase', supplier: 'Supplier', product: 'Product', type: 'Type', qty: 'Qty', before: 'Before', after: 'After', noSale: 'No sale recorded yet.', noPurchase: 'No purchase recorded yet.', printSavePdf: 'Print / Save PDF', downloadPdf: 'Download PDF', back: 'Back', close: 'Close', report: 'Report', generated: 'Generated', billTo: 'Bill To', prescription: 'Prescription', subtotal: 'Subtotal', discount: 'Discount', tax: 'Tax', thankYou: 'Thank you for shopping with us.', pdfHint: 'Use Download PDF or browser print dialog to save this page as PDF.', uploadImages: 'Upload Images', uploadPhoto: 'Upload Photo', optional: 'Optional', chooseImages: 'Choose images', choosePhoto: 'Choose photo', preview: 'Preview', remove: 'Remove', adminPhoto: 'Admin/User Photo', addProduct: 'Add Product', editProduct: 'Edit Product', productInformation: 'Product Information', medicineDetails: 'Medicine Details', glassDetails: 'Glass Details', dashboardHeroTitle: 'Premium optical shop command center', dashboardHeroText: 'Monitor sales, purchases, stock health, expiry alerts and recent movements from one clean dashboard.', actionCompleted: 'Action completed', actionFailed: 'Action failed', noDataFound: 'No data found.' },
    bn: {
        dashboard: 'ড্যাশবোর্ড', products: 'পণ্যসমূহ', purchases: 'ক্রয় / স্টক ইন', stockAdjustments: 'স্টক সমন্বয়', salesInvoice: 'বিক্রয় ও ইনভয়েস', reports: 'রিপোর্ট', suppliers: 'সাপ্লায়ার', categories: 'ক্যাটাগরি', security: 'নিরাপত্তা', usersAccess: 'ইউজার ও এক্সেস', activityLogs: 'অ্যাক্টিভিটি লগ', notifications: 'সিস্টেম নোটিফিকেশন', lowStockProducts: 'কম স্টকের পণ্য', expiringMedicines: '১ মাসের মধ্যে মেয়াদ শেষ হবে', expiredMedicines: 'মেয়াদোত্তীর্ণ ওষুধ', language: 'ভাষা', english: 'English', bangla: 'বাংলা', logout: 'লগআউট', shopSubtitle: 'চক্ষু সেবা ও অপটিক্যাল দোকান ম্যানেজমেন্ট', totalProducts: 'মোট পণ্য', medicines: 'ওষুধ', glassItems: 'গ্লাস আইটেম', lowStock: 'কম স্টক', expiringSoon: 'মেয়াদ শেষ হবে', todaySales: 'আজকের বিক্রয়', monthlySales: 'মাসিক বিক্রয়', todayPurchase: 'আজকের ক্রয়', monthlyPurchase: 'মাসিক ক্রয়', quickOverview: 'দ্রুত সারাংশ', inventoryHealth: 'স্টক অবস্থা', businessSummary: 'ব্যবসার সারাংশ', recentSales: 'সাম্প্রতিক বিক্রয়', recentPurchases: 'সাম্প্রতিক ক্রয় / স্টক ইন', recentStockMovements: 'সাম্প্রতিক স্টক মুভমেন্ট', noLowStock: 'কম স্টকের কোনো পণ্য নেই।', noExpiring: '১ মাসের মধ্যে মেয়াদ শেষ হবে এমন ওষুধ নেই।', invoice: 'ইনভয়েস', customer: 'কাস্টমার', total: 'মোট', paid: 'পরিশোধ', due: 'বাকি', status: 'স্ট্যাটাস', purchase: 'ক্রয়', supplier: 'সাপ্লায়ার', product: 'পণ্য', type: 'ধরন', qty: 'পরিমাণ', before: 'আগে', after: 'পরে', noSale: 'এখনও কোনো বিক্রয় নেই।', noPurchase: 'এখনও কোনো ক্রয় নেই।', printSavePdf: 'প্রিন্ট / PDF সেভ', downloadPdf: 'PDF ডাউনলোড', back: 'ফিরে যান', close: 'বন্ধ', report: 'রিপোর্ট', generated: 'তৈরি হয়েছে', billTo: 'বিল প্রাপক', prescription: 'চশমার প্রেসক্রিপশন', subtotal: 'সাবটোটাল', discount: 'ডিসকাউন্ট', tax: 'ট্যাক্স', thankYou: 'আমাদের সাথে কেনাকাটার জন্য ধন্যবাদ।', pdfHint: 'PDF হিসেবে সেভ করতে Download PDF বা ব্রাউজার প্রিন্ট ব্যবহার করুন।', uploadImages: 'ছবি আপলোড', uploadPhoto: 'ছবি আপলোড', optional: 'ঐচ্ছিক', chooseImages: 'ছবি নির্বাচন করুন', choosePhoto: 'ছবি নির্বাচন করুন', preview: 'প্রিভিউ', remove: 'মুছে ফেলুন', adminPhoto: 'অ্যাডমিন/ইউজার ছবি', addProduct: 'পণ্য যোগ করুন', editProduct: 'পণ্য এডিট করুন', productInformation: 'পণ্যের তথ্য', medicineDetails: 'ওষুধের তথ্য', glassDetails: 'গ্লাসের তথ্য', dashboardHeroTitle: 'প্রিমিয়াম অপটিক্যাল শপ কমান্ড সেন্টার', dashboardHeroText: 'বিক্রয়, ক্রয়, স্টক, মেয়াদ সতর্কতা এবং সাম্প্রতিক মুভমেন্ট এক জায়গা থেকে দেখুন।', actionCompleted: 'কাজ সম্পন্ন হয়েছে', actionFailed: 'কাজ ব্যর্থ হয়েছে', noDataFound: 'কোনো ডাটা পাওয়া যায়নি।' },
};

export function useI18n() {
    const locale = usePage().props.locale || 'en';
    const t = (key) => translations[locale]?.[key] || translations.en[key] || key;
    return { locale, t };
}

export function label(key, locale = 'en') {
    return translations[locale]?.[key] || translations.en[key] || key;
}
