import { Link } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { Icon } from '@/Components/Icons';

export default function Dashboard({ stats = {}, messages = [], appointments = [] }) {
    const cards = [
        ['Hero Banners', stats.slides, 'sparkles', '/website-admin/hero-slides'], ['Services', stats.services, 'eye', '/website-admin/services'], ['Gallery', stats.gallery, 'image', '/website-admin/gallery'], ['Testimonials', stats.testimonials, 'users', '/website-admin/testimonials'], ['Website Products', stats.website_products, 'box', '/shop-admin/products'], ['New Messages', stats.new_messages, 'file', '/website-admin/messages'], ['Pending Appointments', stats.pending_appointments, 'calendar', '/website-admin/appointments'],
    ];
    return <AdminLayout title="Website Management"><section className="rounded-[2rem] bg-gradient-to-r from-blue-600 to-cyan-500 p-8 text-white shadow-xl shadow-blue-600/20"><h2 className="text-3xl font-black">Dynamic public website control center</h2><p className="mt-2 max-w-3xl text-white/80">Manage homepage content, hero banners, services, gallery, product visibility, testimonials, messages and appointment requests from one place.</p><Link href="/" className="mt-6 inline-flex rounded-full bg-white px-5 py-3 text-sm font-black text-blue-700">View Website</Link></section><div className="mt-6 grid gap-4 md:grid-cols-4">{cards.map(([label,value,icon,href])=><Link href={href} key={label} className="rounded-[2rem] bg-white p-5 shadow-sm ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800"><div className="flex items-center justify-between"><div className="text-sm font-bold text-slate-500">{label}</div><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-blue-600 dark:bg-blue-500/10"><Icon name={icon}/></div></div><div className="mt-4 text-3xl font-black">{value ?? 0}</div></Link>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Latest Messages" rows={messages}/><Panel title="Latest Appointments" rows={appointments}/></div></AdminLayout>;
}
function Panel({title,rows}){return <div className="rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800"><h3 className="text-lg font-black">{title}</h3><div className="mt-4 space-y-3">{rows.length?rows.map(r=><div key={r.id} className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><div className="font-black">{r.name}</div><div className="text-sm text-slate-500">{r.phone || r.email || r.status}</div></div>):<p className="text-sm text-slate-500">No data found.</p>}</div></div>}
