import { useForm } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { Input, Textarea } from '@/Components/Input';

export default function Settings({ settings }) {
    const { data, setData, post, processing, errors } = useForm({
        site_name: settings?.site_name ?? 'Madina Optical', tagline: settings?.tagline ?? '', tagline_bn: settings?.tagline_bn ?? '', short_description: settings?.short_description ?? '', short_description_bn: settings?.short_description_bn ?? '', phone: settings?.phone ?? '', whatsapp: settings?.whatsapp ?? '', email: settings?.email ?? '', address: settings?.address ?? '', address_bn: settings?.address_bn ?? '', opening_hours: settings?.opening_hours ?? '', facebook_url: settings?.facebook_url ?? '', google_map_url: settings?.google_map_url ?? '', seo_title: settings?.seo_title ?? '', seo_title_bn: settings?.seo_title_bn ?? '', seo_description: settings?.seo_description ?? '', seo_description_bn: settings?.seo_description_bn ?? '', logo: null, favicon: null,
    });
    const submit = e => { e.preventDefault(); post('/website-admin/settings', { forceFormData: true }); };
    return <AdminLayout title="Website Settings"><form onSubmit={submit} className="space-y-6 rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800"><div className="grid gap-4 md:grid-cols-3"><Input label="Site Name" value={data.site_name} onChange={e=>setData('site_name',e.target.value)} error={errors.site_name}/><Input label="Phone" value={data.phone} onChange={e=>setData('phone',e.target.value)} /><Input label="WhatsApp" value={data.whatsapp} onChange={e=>setData('whatsapp',e.target.value)} /><Input label="Email" value={data.email} onChange={e=>setData('email',e.target.value)} error={errors.email}/><Input label="Opening Hours" value={data.opening_hours} onChange={e=>setData('opening_hours',e.target.value)} /><Input label="Facebook URL" value={data.facebook_url} onChange={e=>setData('facebook_url',e.target.value)} error={errors.facebook_url}/></div><div className="grid gap-4 md:grid-cols-2"><Input label="Tagline" value={data.tagline} onChange={e=>setData('tagline',e.target.value)} /><Input label="Tagline Bangla" value={data.tagline_bn} onChange={e=>setData('tagline_bn',e.target.value)} /><Textarea label="Short Description" value={data.short_description} onChange={e=>setData('short_description',e.target.value)} /><Textarea label="Short Description Bangla" value={data.short_description_bn} onChange={e=>setData('short_description_bn',e.target.value)} /><Textarea label="Address" value={data.address} onChange={e=>setData('address',e.target.value)} /><Textarea label="Address Bangla" value={data.address_bn} onChange={e=>setData('address_bn',e.target.value)} /><Input label="SEO Title" value={data.seo_title} onChange={e=>setData('seo_title',e.target.value)} /><Input label="SEO Title Bangla" value={data.seo_title_bn} onChange={e=>setData('seo_title_bn',e.target.value)} /><Textarea label="SEO Description" value={data.seo_description} onChange={e=>setData('seo_description',e.target.value)} /><Textarea label="SEO Description Bangla" value={data.seo_description_bn} onChange={e=>setData('seo_description_bn',e.target.value)} /></div><div className="grid gap-4 md:grid-cols-2"><Input label="Logo" type="file" onChange={e=>setData('logo',e.target.files[0])} error={errors.logo}/><Input label="Favicon" type="file" onChange={e=>setData('favicon',e.target.files[0])} error={errors.favicon}/></div><button disabled={processing} className="rounded-2xl bg-blue-600 px-6 py-3 font-black text-white">Save Website Settings</button></form></AdminLayout>;
}
